enum ChatMessageSender { user, ai }

// Define the type of input that generated the message
enum InputType { text, ocr, url, question } // Added question type

class ChatMessage {
  final String id;
  final String text; // The actual full text content
  final ChatMessageSender sender;
  final DateTime timestamp;
  final bool isPlaceholderSummary; // For AI responses to OCR
  final String? displayOverride; // Transient field for UI override on load
  final InputType inputType; // Added: Store the original input type

  ChatMessage({
    required this.id,
    required this.text,
    required this.sender,
    required this.timestamp,
    this.isPlaceholderSummary = false,
    this.displayOverride, 
    this.inputType = InputType.text, // Default to text
  });

  // Converts a ChatMessage to a Map for Supabase insertion into 'chat_messages' table
  Map<String, dynamic> toJsonForDb(String sessionId, String userId) {
    // displayOverride is NOT saved to the database
    return {
      'session_id': sessionId,
      'user_id': userId, // The user who owns this session/message
      'sender': sender == ChatMessageSender.user ? 'user' : 'ai',
      'content': text,
      'timestamp': timestamp.toIso8601String(),
      'is_placeholder_summary': isPlaceholderSummary,
      'input_type': inputType.name, // Save enum name as string
      // The 'id' for the chat_messages table row will be auto-generated by Supabase (UUID)
    };
  }

  // Helper to convert string from DB back to enum
  static InputType inputTypeFromString(String? typeString) {
    if (typeString == null) return InputType.text;
    return InputType.values.firstWhere(
      (e) => e.name == typeString,
      orElse: () => InputType.text, // Default if unknown type from DB
    );
  }

  // Optional: Add fromJson/toJson methods if you plan to serialize this model,
  // for example, when saving chat history to Supabase.
  // Map<String, dynamic> toJson() => {
  //   'id': id,
  //   'text': text,
  //   'sender': sender.toString(), // or sender.name in Dart 3
  //   'timestamp': timestamp.toIso8601String(),
  // };

  // factory ChatMessage.fromJson(Map<String, dynamic> json) => ChatMessage(
  //   id: json['id'],
  //   text: json['text'],
  //   sender: ChatMessageSender.values.firstWhere((e) => e.toString() == json['sender']),
  //   timestamp: DateTime.parse(json['timestamp']),
  // );
} 